package com.agon.app.ui.theme

import androidx.compose.ui.graphics.Color

// ---------------------------------------------------------------------------
// BlockX LaAbrah — "Shield Emerald" visual identity.
// Deep emerald signals protection and trust; warm amber is reserved for
// warnings and highlights; red appears only for genuinely dangerous states.
// ---------------------------------------------------------------------------

// Light scheme — botanical, calm, high contrast for outdoor readability.
val ShieldPrimaryLight = Color(0xFF0E5B45)
val ShieldOnPrimaryLight = Color(0xFFFFFFFF)
val ShieldPrimaryContainerLight = Color(0xFFA9F2CB)
val ShieldOnPrimaryContainerLight = Color(0xFF022016)
val ShieldSecondaryLight = Color(0xFF4C6358)
val ShieldOnSecondaryLight = Color(0xFFFFFFFF)
val ShieldSecondaryContainerLight = Color(0xFFCEE9DA)
val ShieldOnSecondaryContainerLight = Color(0xFF092016)
val ShieldTertiaryLight = Color(0xFF875512)
val ShieldOnTertiaryLight = Color(0xFFFFFFFF)
val ShieldTertiaryContainerLight = Color(0xFFFFDDBA)
val ShieldOnTertiaryContainerLight = Color(0xFF2A1700)
val ShieldErrorLight = Color(0xFFBA1A1A)
val ShieldOnErrorLight = Color(0xFFFFFFFF)
val ShieldErrorContainerLight = Color(0xFFFFDAD6)
val ShieldOnErrorContainerLight = Color(0xFF410002)
val ShieldBackgroundLight = Color(0xFFF4FAF6)
val ShieldOnBackgroundLight = Color(0xFF151D19)
val ShieldSurfaceLight = Color(0xFFF4FAF6)
val ShieldOnSurfaceLight = Color(0xFF151D19)
val ShieldSurfaceVariantLight = Color(0xFFDCE5DD)
val ShieldOnSurfaceVariantLight = Color(0xFF404942)
val ShieldOutlineLight = Color(0xFF707972)
val ShieldOutlineVariantLight = Color(0xFFC0C9C1)
val ShieldSurfaceDimLight = Color(0xFFD5DBD7)
val ShieldSurfaceBrightLight = Color(0xFFF4FAF6)
val ShieldSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val ShieldSurfaceContainerLowLight = Color(0xFFEFF5F1)
val ShieldSurfaceContainerLight = Color(0xFFE9F0EB)
val ShieldSurfaceContainerHighLight = Color(0xFFE4EAE5)
val ShieldSurfaceContainerHighestLight = Color(0xFFDEE5DF)
val ShieldInverseSurfaceLight = Color(0xFF2A322D)
val ShieldInverseOnSurfaceLight = Color(0xFFEBF2ED)
val ShieldInversePrimaryLight = Color(0xFF8DDBB2)

// Dark scheme — deep charcoal with a green cast; emerald on top stays luminous.
val ShieldPrimaryDark = Color(0xFF8DDBB2)
val ShieldOnPrimaryDark = Color(0xFF00391F)
val ShieldPrimaryContainerDark = Color(0xFF0B5133)
val ShieldOnPrimaryContainerDark = Color(0xFFA9F2CB)
val ShieldSecondaryDark = Color(0xFFB3CCBC)
val ShieldOnSecondaryDark = Color(0xFF1F3527)
val ShieldSecondaryContainerDark = Color(0xFF354B3C)
val ShieldOnSecondaryContainerDark = Color(0xFFCEE9DA)
val ShieldTertiaryDark = Color(0xFFFBBE6B)
val ShieldOnTertiaryDark = Color(0xFF482900)
val ShieldTertiaryContainerDark = Color(0xFF683D05)
val ShieldOnTertiaryContainerDark = Color(0xFFFFDDC0)
val ShieldErrorDark = Color(0xFFFFB4AB)
val ShieldOnErrorDark = Color(0xFF690005)
val ShieldErrorContainerDark = Color(0xFF93000A)
val ShieldOnErrorContainerDark = Color(0xFFFFDAD6)
val ShieldBackgroundDark = Color(0xFF0C120F)
val ShieldOnBackgroundDark = Color(0xFFDDE5DF)
val ShieldSurfaceDark = Color(0xFF0C120F)
val ShieldOnSurfaceDark = Color(0xFFDDE5DF)
val ShieldSurfaceVariantDark = Color(0xFF404942)
val ShieldOnSurfaceVariantDark = Color(0xFFBFC9C1)
val ShieldOutlineDark = Color(0xFF89938B)
val ShieldOutlineVariantDark = Color(0xFF404942)
val ShieldSurfaceDimDark = Color(0xFF0C120F)
val ShieldSurfaceBrightDark = Color(0xFF323833)
val ShieldSurfaceContainerLowestDark = Color(0xFF070B08)
val ShieldSurfaceContainerLowDark = Color(0xFF141B17)
val ShieldSurfaceContainerDark = Color(0xFF181F1B)
val ShieldSurfaceContainerHighDark = Color(0xFF222A25)
val ShieldSurfaceContainerHighestDark = Color(0xFF2C342F)
val ShieldInverseSurfaceDark = Color(0xFFDDE5DF)
val ShieldInverseOnSurfaceDark = Color(0xFF2A322D)
val ShieldInversePrimaryDark = Color(0xFF0E5B45)
