package com.agon.app.localization

import androidx.compose.runtime.staticCompositionLocalOf

val LocalAppLanguage = staticCompositionLocalOf { "ku" }

private val textResolver: (String, String) -> String = run {
    val ku = mapOf(
        "Blocklist" to "بلۆکلیست", "Control what is allowed" to "کۆنترۆڵی ناوەڕۆکی ڕێگەپێدراو", "All" to "هەموو", "Websites" to "وێبسایتەکان", "Apps" to "ئەپەکان",
        "Keywords" to "وشە کلیلییەکان", "Block" to "بلۆک", "Whitelist" to "لیستی سپی", "Add Sites" to "زیادکردنی وێبسایت",
        "No items yet" to "هێشتا هیچ دانەیەک نییە", "No matching items" to "هیچ ئەنجامێک نییە", "Recent" to "نوێترین", "Oldest" to "کۆنترین",
        "Edit keyword" to "دەستکاری وشەی کلیلی", "Keyword" to "وشەی کلیلی", "Cancel" to "پاشگەزبوونەوە", "Save" to "پاشەکەوتکردن",
        "Search installed apps" to "گەڕان لە ئەپە دامەزراوەکان", "Item deleted" to "دانەکە سڕایەوە", "%d items deleted" to "%d دانە سڕایەوە",
        "Undo" to "گەڕاندنەوە", "%d selected" to "%d هەڵبژێردراوە", "Clear selection" to "پاککردنەوەی هەڵبژاردن", "Delete selected" to "سڕینەوەی هەڵبژێردراوەکان",
        "AI classification settings" to "ڕێکخستنی پۆلێنکردنی زیرەک", "Add sites" to "زیادکردنی وێبسایت", "Search blocklist" to "گەڕان لە بلۆکلیست",
        "Search whitelist" to "گەڕان لە لیستی سپی", "Clear search" to "پاککردنەوەی گەڕان", "Sort" to "ڕیزکردن",
        "Add items to your blocklist." to "وێبسایت، ئەپ یان وشە بۆ بلۆکلیست زیاد بکە.", "Add items to your whitelist." to "وێبسایت، ئەپ یان وشە بۆ لیستی سپی زیاد بکە.",
        "Try another search or filter." to "گەڕان یان پاڵاوتنێکی تر تاقی بکەوە.", "Delete" to "سڕینەوە", "Selected" to "هەڵبژێردراو", "Options" to "هەڵبژاردەکان",
        "Website" to "وێبسایت", "Add to Blocklist" to "زیادکردن بۆ بلۆکلیست", "Add to Whitelist" to "زیادکردن بۆ لیستی سپی", "Sites" to "وێبسایتەکان", "Words" to "وشەکان",
        "Enter one or more domains" to "یەک یان چەند دۆمەینێک بنووسە", "Separate domains with a new line, comma, or space." to "دۆمەینەکان بە هێڵی نوێ، کۆما یان بۆشایی جیا بکەوە.",
        "Add keywords" to "زیادکردنی وشە کلیلی", "Separate multiple keywords with a new line or comma." to "وشەکان بە هێڵی نوێ یان کۆما جیا بکەوە.",
        "Enter keywords" to "وشە کلیلییەکان بنووسە", "Enter at least one domain" to "لانیکەم یەک دۆمەین بنووسە", "Invalid domain: %s" to "دۆمەینی نادروست: %s",
        "Enter at least one keyword" to "لانیکەم یەک وشە بنووسە", "Add %d apps" to "زیادکردنی %d ئەپ", "Add Apps" to "زیادکردنی ئەپ", "Add Keywords" to "زیادکردنی وشە کلیلی",
        "Smart classification" to "پۆلێنکردنی زیرەک", "Block at %d%% confidence" to "بلۆککردن لە دڵنیایی %d%%", "Done" to "تەواو",
        "Adult content" to "ناوەڕۆکی گەورەساڵان", "Gambling" to "قومار", "Drugs" to "ماددە هۆشبەرەکان", "Violence" to "توندوتیژی", "Hate" to "ڕق",
        "Scam" to "فێڵ", "Phishing" to "فیشینگ", "Malware" to "نەرمەکاڵای زیانبەخش", "Extremism" to "توندڕەوی",
        "Blocked keyword" to "وشەی بلۆککراو", "Website rule" to "یاسای وێبسایت", "Blocked domain" to "دۆمەینی بلۆککراو", "Circumvention blocked" to "تێپەڕاندن بلۆک کرا",
        // ---- home dashboard ----
        "سڵاو" to "سڵاو",
        "دۆخی پاراستن" to "دۆخی پاراستن",
        "پاراستن چالاکە" to "پاراستن چالاکە",
        "پاراستن لەکارخراوە" to "پاراستن لەکارخراوە",
        "هەموو قەپاغەکان بە باشی کاردەکەن" to "هەموو قەپاغەکان بە باشی کاردەکەن",
        "پاراستن ناچالاکە، پاراستن چالاک بکە" to "پاراستن ناچالاکە، پاراستن چالاک بکە",
        "دۆخی پاراستنی ئامێرەکەت لێرەیە" to "دۆخی پاراستنی ئامێرەکەت لێرەیە",
        "ئاگاداریی ئاسایش" to "ئاگاداریی ئاسایش",
        "ئامێرەکە پارێزراوە" to "ئامێرەکە پارێزراوە",
        "نیشانەی Root لەم ئامێرە دۆزرایەوە. ئەمە دەتوانێت پاراستن لاواز بکات." to "نیشانەی Root لەم ئامێرە دۆزرایەوە. ئەمە دەتوانێت پاراستن لاواز بکات.",
        "هیچ نیشانەیەکی Root نەدۆزرایەوە." to "هیچ نیشانەیەکی Root نەدۆزرایەوە.",
        "باشە" to "باشە",
        "پاراستنی براوزەر" to "پاراستنی براوزەر",
        "مۆڵەت دراوە" to "مۆڵەت دراوە",
        "پێویستی بە مۆڵەتە" to "پێویستی بە مۆڵەتە",
        "داواکاری پشکنراو" to "داواکاری پشکنراو",
        "بلۆککراو" to "بلۆککراو",
        // ---- history ----
        "مێژووی پاراستن" to "مێژووی پاراستن",
        "ڕۆژانە" to "ڕۆژانە", "هەفتانە" to "هەفتانە", "مانگانە" to "مانگانە",
        "کۆی بلۆککردنەکان" to "کۆی بلۆککردنەکان",
        "دوایین ڕووداوەکان" to "دوایین ڕووداوەکان",
        "هێشتا هیچ شتێک بلۆک نەکراوە" to "هێشتا هیچ شتێک بلۆک نەکراوە",
        "ڕووداوەکان لێرە دەردەکەون" to "ڕووداوەکان لێرە دەردەکەون",
        // ---- settings ----
        "ڕێکخستن" to "ڕێکخستن",
        "هەموو قەپاغەکانی پاراستن لێرەیە" to "هەموو قەپاغەکانی پاراستن لێرەیە",
        "ڕووکار، زمان و تێبینیەکان" to "ڕووکار، زمان و تێبینیەکان",
        "دۆخی ڕووکار" to "دۆخی ڕووکار",
        "سیستەم" to "سیستەم", "ڕووناک" to "ڕووناک", "تاریک" to "تاریک",
        "زمان" to "زمان",
        "تایبەتمەندی" to "تایبەتمەندی",
        "BlockX LaAbrah تەنها ناونیشانی تۆڕ و دەقی دیاریکراوی براوزەر دەپشکنێت. هیچ داتایەک بۆ سێرڤەری تایبەت نانێردرێت و مێژوو لەسەر ئامێرەکەت دەمێنێتەوە." to "BlockX LaAbrah تەنها ناونیشانی تۆڕ و دەقی دیاریکراوی براوزەر دەپشکنێت. هیچ داتایەک بۆ سێرڤەری تایبەت نانێردرێت و مێژوو لەسەر ئامێرەکەت دەمێنێتەوە.",
        "BlockX LaAbrah · وەشانی 2.1.11" to "BlockX LaAbrah · وەشانی 2.1.11",
        "مۆڵەتی ئەدمین" to "مۆڵەتی ئەدمین",
        "مۆڵەت دراوە - بەڕێوەبردن لە Settings ـی ئەندرۆید" to "مۆڵەت دراوە - بەڕێوەبردن لە Settings ـی ئەندرۆید",
        "بەڕێوەبردن لە Settings ـی ئەندرۆید" to "بەڕێوەبردن لە Settings ـی ئەندرۆید",
        "Accessibility Service" to "Accessibility Service",
        "پاراستنی زیادە بۆ براوزەرەکان" to "پاراستنی زیادە بۆ براوزەرەکان",
        "فێرکاری مۆڵەتەکان" to "فێرکاری مۆڵەتەکان",
        "هەنگاوەکانی Accessibility و Device Admin و باتری ببینەوە." to "هەنگاوەکانی Accessibility و Device Admin و باتری ببینەوە.",
        "وەستاندنی پاراستن (٣ خولەک)" to "وەستاندنی پاراستن (٣ خولەک)",
        "دوای %d خولەک دەگەڕێتەوە - بۆ گەڕانەوە دەستبکە" to "دوای %d خولەک دەگەڕێتەوە - بۆ گەڕانەوە دەستبکە",
        "کاتی دەیکوژێنێتەوە، خۆکارانە دەگەڕێتەوە" to "کاتی دەیکوژێنێتەوە، خۆکارانە دەگەڕێتەوە",
        "سپیەری تۆڕ هەموو داواکارییەکان دەپشکنێت" to "سپیەری تۆڕ هەموو داواکارییەکان دەپشکنێت", "سپیەری تۆڕ ناچالاکە" to "سپیەری تۆڕ ناچالاکە",
        "سپیەری تۆڕ" to "سپیەری تۆڕ", "سپیەری تۆڕ خۆکارانە دەست پێ بکات" to "سپیەری تۆڕ خۆکارانە دەست پێ بکات", "پاراستنی ئامێرەکەت" to "پاراستنی ئامێرەکەت", "ڤیدیۆ کورتەکان" to "ڤیدیۆ کورتەکان",
    )
    val en = mapOf(
        "سەرەکی" to "Home", "بلۆکلیست" to "Blocklist", "کات" to "Time", "مێژوو" to "History", "ڕیلز" to "Reels", "ڤیدیۆ کورتەکان" to "Short videos", "ڕێکخستن" to "Settings",
        "پاراستنی ئامێرەکەت" to "Protection for your device", "پارێزراوە" to "Protected", "پاراستن ناچالاکە" to "Protection is off",
        "سپیەری تۆڕ هەموو داواکارییەکان دەپشکنێت" to "Safe Browsing Shield is checking all requests", "سپیەری تۆڕ ناچالاکە" to "Safe Browsing Shield is inactive",
        "وەستاندنی پاراستن" to "Stop protection", "چالاککردنی پاراستن" to "Enable protection", "داواکاری پشکنراو" to "Requests checked", "بلۆککراو" to "Blocked",
        "چالاکە" to "Active", "ناچالاکە" to "Inactive", "مۆڵەت دراوە" to "Permission granted", "پێویستی بە مۆڵەتە" to "Permission required", "پاراستنی براوزەر" to "Browser protection",
        "ڕێکخستن" to "Settings", "پاراستن" to "Protection", "چالاکبوون دوای Restart" to "Start after restart", "سپیەری تۆڕ خۆکارانە دەست پێ بکات" to "Start Safe Browsing Shield automatically",
        "ڕووکار و زمان" to "Appearance and language", "دۆخی ڕووکار" to "Theme", "سیستەم" to "System", "ڕووناک" to "Light", "تاریک" to "Dark", "زمان" to "Language",
        "Blocklist" to "Blocklist", "Control what is allowed" to "Control what is allowed",
        "All" to "All", "Websites" to "Websites", "Apps" to "Apps", "Keywords" to "Keywords", "Block" to "Block", "Whitelist" to "Whitelist", "Add Sites" to "Add Sites",
        "No items yet" to "No items yet", "No matching items" to "No matching items", "Recent" to "Recent", "Oldest" to "Oldest", "A–Z" to "A–Z", "Z–A" to "Z–A",
        "Edit keyword" to "Edit keyword", "Keyword" to "Keyword", "Cancel" to "Cancel", "Save" to "Save", "Search installed apps" to "Search installed apps",
        "زانیاری" to "Information", "سپیەری تۆڕ" to "Safe Browsing Shield", "ماوەی پاراستن" to "Protection duration",
        "ئاگاداریی ئاسایش" to "Security warning", "ئامێرەکە پارێزراوە" to "Device is secure",
        "نیشانەی Root لەم ئامێرە دۆزرایەوە. ئەمە دەتوانێت پاراستن لاواز بکات." to "Root access was detected on this device. This can weaken protection.",
        "هیچ نیشانەیەکی Root نەدۆزرایەوە." to "No signs of root access were found.", "باشە" to "OK",
        "مێژووی پاراستن" to "Protection history", "ڕۆژانە" to "Daily", "هەفتانە" to "Weekly", "مانگانە" to "Monthly",
        "کۆی بلۆککردنەکان" to "Total blocks", "دوایین ڕووداوەکان" to "Recent events",
        "هێشتا هیچ شتێک بلۆک نەکراوە" to "Nothing has been blocked yet", "ڕووداوەکان لێرە دەردەکەون" to "Events will appear here",
        "Accessibility Service" to "Accessibility service", "پاراستنی زیادە بۆ براوزەرەکان" to "Additional browser protection",
        "مۆڵەتی ئەدمین" to "Device administrator", "مۆڵەت دراوە - بەڕێوەبردن لە Settings ـی ئەندرۆید" to "Granted — manage in Android Settings",
        "بەڕێوەبردن لە Settings ـی ئەندرۆید" to "Manage in Android Settings", "تایبەتمەندی" to "Privacy",
        "BlockX LaAbrah تەنها ناونیشانی تۆڕ و دەقی دیاریکراوی براوزەر دەپشکنێت. هیچ داتایەک بۆ سێرڤەری تایبەت نانێردرێت و مێژوو لەسەر ئامێرەکەت دەمێنێتەوە." to "BlockX LaAbrah checks only network addresses and selected browser text. No data is sent to a private server, and history stays on your device.",
        "هیچ داتایەک بۆ سێرڤەر نانێردرێت؛ هەموو شتێک لەسەر ئامێرەکەت دەمێنێتەوە." to "No data is sent to any server; everything stays on your device.",
        "BlockX LaAbrah · وەشانی 1.0" to "BlockX LaAbrah · Version 1.0",
        "Item deleted" to "Item deleted", "%d items deleted" to "%d items deleted", "Undo" to "Undo", "%d selected" to "%d selected",
        "Clear selection" to "Clear selection", "Delete selected" to "Delete selected", "AI classification settings" to "AI classification settings",
        "Add sites" to "Add sites", "Search blocklist" to "Search blocklist", "Search whitelist" to "Search whitelist", "Clear search" to "Clear search", "Sort" to "Sort",
        "Add items to your blocklist." to "Add websites, apps, or keywords to your blocklist.", "Add items to your whitelist." to "Add websites, apps, or keywords to your whitelist.",
        "Try another search or filter." to "Try another search or filter.", "Delete" to "Delete", "Selected" to "Selected", "Options" to "Options", "Website" to "Website",
        "Add to Blocklist" to "Add to Blocklist", "Add to Whitelist" to "Add to Whitelist", "Sites" to "Sites", "Words" to "Words",
        "Enter one or more domains" to "Enter one or more domains", "Separate domains with a new line, comma, or space." to "Separate domains with a new line, comma, or space.",
        "Add keywords" to "Add keywords", "Separate multiple keywords with a new line or comma." to "Separate multiple keywords with a new line or comma.",
        "Enter keywords" to "Enter keywords", "Enter at least one domain" to "Enter at least one domain", "Invalid domain: %s" to "Invalid domain: %s",
        "Enter at least one keyword" to "Enter at least one keyword", "Add %d apps" to "Add %d apps", "Add Apps" to "Add Apps", "Add Keywords" to "Add Keywords",
        "Smart classification" to "Smart classification", "Block at %d%% confidence" to "Block at %d%% confidence", "Done" to "Done",
        "Adult content" to "Adult content", "Gambling" to "Gambling", "Drugs" to "Drugs", "Violence" to "Violence", "Hate" to "Hate",
        "Scam" to "Scam", "Phishing" to "Phishing", "Malware" to "Malware", "Extremism" to "Extremism",
        "Blocked keyword" to "Blocked keyword", "Website rule" to "Website rule", "Blocked domain" to "Blocked domain", "Circumvention blocked" to "Circumvention blocked",
        // ---- home dashboard ----
        "سڵاو" to "Hello",
        "دۆخی پاراستن" to "Protection status",
        "پاراستن چالاکە" to "Protection is active",
        "پاراستن لەکارخراوە" to "Protection is paused",
        "هەموو قەپاغەکان بە باشی کاردەکەن" to "All shields are running smoothly",
        "پاراستن ناچالاکە، پاراستن چالاک بکە" to "Protection is off. Enable protection to stay safe.",
        "دۆخی پاراستنی ئامێرەکەت لێرەیە" to "Your device protection at a glance",
        "ئاگاداریی ئاسایش" to "Security warning",
        "ئامێرەکە پارێزراوە" to "Device is secure",
        "نیشانەی Root لەم ئامێرە دۆزرایەوە. ئەمە دەتوانێت پاراستن لاواز بکات." to "Root access was detected on this device. This can weaken protection.",
        "هیچ نیشانەیەکی Root نەدۆزرایەوە." to "No signs of root access were found.",
        "باشە" to "OK",
        "پاراستنی براوزەر" to "Browser protection",
        "مۆڵەت دراوە" to "Permission granted",
        "پێویستی بە مۆڵەتە" to "Permission required",
        "داواکاری پشکنراو" to "Requests checked",
        "بلۆککراو" to "Blocked",
        // ---- history ----
        "مێژووی پاراستن" to "Protection history",
        "ڕۆژانە" to "Daily", "هەفتانە" to "Weekly", "مانگانە" to "Monthly",
        "کۆی بلۆککردنەکان" to "Total blocks",
        "دوایین ڕووداوەکان" to "Recent events",
        "هێشتا هیچ شتێک بلۆک نەکراوە" to "Nothing has been blocked yet",
        "ڕووداوەکان لێرە دەردەکەون" to "Events will appear here",
        // ---- settings ----
        "ڕێکخستن" to "Settings",
        "هەموو قەپاغەکانی پاراستن لێرەیە" to "All protection shields live here",
        "ڕووکار، زمان و تێبینیەکان" to "Theme, language and preferences",
        "دۆخی ڕووکار" to "Theme",
        "سیستەم" to "System", "ڕووناک" to "Light", "تاریک" to "Dark",
        "زمان" to "Language",
        "تایبەتمەندی" to "Privacy",
        "BlockX LaAbrah تەنها ناونیشانی تۆڕ و دەقی دیاریکراوی براوزەر دەپشکنێت. هیچ داتایەک بۆ سێرڤەری تایبەت نانێردرێت و مێژوو لەسەر ئامێرەکەت دەمێنێتەوە." to "BlockX LaAbrah checks only network addresses and selected browser text. No data is sent to a private server, and history stays on your device.",
        "BlockX LaAbrah · وەشانی 2.1.11" to "BlockX LaAbrah · Version 2.1.11",
        "مۆڵەتی ئەدمین" to "Device administrator",
        "مۆڵەت دراوە - بەڕێوەبردن لە Settings ـی ئەندرۆید" to "Granted — manage in Android Settings",
        "بەڎوەبردن لە Settings ـی ئەندرۆید" to "Manage in Android Settings",
        "Accessibility Service" to "Accessibility service",
        "پاراستنی زیادە بۆ براوزەرەکان" to "Additional protection for browsers",
        "فێرکاری مۆڵەتەکان" to "Permission tutorial",
        "هەنگاوەکانی Accessibility و Device Admin و باتری ببینەوە." to "Review Accessibility, Device Admin and battery steps.",
        "وەستاندنی پاراستن (٣ خولەک)" to "Pause protection (3 min)",
        "دوای %d خولەک دەگەڕێتەوە - بۆ گەڕانەوە دەستبکە" to "Resumes in %d min — tap to resume now",
        "کاتی دەیکوژێنێتەوە، خۆکارانە دەگەڕێتەوە" to "Temporarily turn off — resumes automatically",
    )
    val ar = mapOf(
        "سەرەکی" to "الرئيسية", "بلۆکلیست" to "قائمة الحظر", "کات" to "الوقت", "مێژوو" to "السجل", "ڕیلز" to "حظر الريلز", "ڤیدیۆ کورتەکان" to "الفيديوهات القصيرة", "ڕێکخستن" to "الإعدادات",
        "پاراستنی ئامێرەکەت" to "حماية لجهازك", "پارێزراوە" to "محمي", "پاراستن ناچالاکە" to "الحماية متوقفة",
        "سپیەری تۆڕ هەموو داواکارییەکان دەپشکنێت" to "يفحص درع التصفح الآمن جميع الطلبات", "سپیەری تۆڕ ناچالاکە" to "درع التصفح الآمن غير نشط",
        "وەستاندنی پاراستن" to "إيقاف الحماية", "چالاککردنی پاراستن" to "تفعيل الحماية", "داواکاری پشکنراو" to "طلبات مفحوصة", "بلۆککراو" to "محظور",
        "چالاکە" to "نشط", "ناچالاکە" to "غير نشط", "مۆڵەت دراوە" to "تم منح الإذن", "پێویستی بە مۆڵەتە" to "الإذن مطلوب", "پاراستنی براوزەر" to "حماية المتصفح",
        "پاراستن" to "الحماية", "چالاکبوون دوای Restart" to "التشغيل بعد إعادة التشغيل", "سپیەری تۆڕ خۆکارانە دەست پێ بکات" to "تشغيل درع التصفح الآمن تلقائياً",
        "ڕووکار و زمان" to "المظهر واللغة", "دۆخی ڕووکار" to "المظهر", "سیستەم" to "النظام", "ڕووناک" to "فاتح", "تاریک" to "داكن", "زمان" to "اللغة",
        "Blocklist" to "قائمة الحظر", "Control what is allowed" to "تحكم بالمحتوى المسموح",
        "All" to "الكل", "Websites" to "المواقع", "Apps" to "التطبيقات", "Keywords" to "الكلمات", "Block" to "حظر", "Whitelist" to "القائمة البيضاء", "Add Sites" to "إضافة مواقع",
        "No items yet" to "لا توجد عناصر", "No matching items" to "لا توجد نتائج", "Recent" to "الأحدث", "Oldest" to "الأقدم", "A–Z" to "أ-ي", "Z–A" to "ي-أ",
        "Edit keyword" to "تعديل الكلمة", "Keyword" to "الكلمة", "Cancel" to "إلغاء", "Save" to "حفظ", "Search installed apps" to "البحث في التطبيقات المثبتة",
        "زانیاری" to "معلومات", "سپیەری تۆڕ" to "درع التصفح الآمن", "ماوەی پاراستن" to "مدة الحماية",
        "ئاگاداریی ئاسایش" to "تحذير أمني", "ئامێرەکە پارێزراوە" to "الجهاز آمن",
        "نیشانەی Root لەم ئامێرە دۆزرایەوە. ئەمە دەتوانێت پاراستن لاواز بکات." to "تم اكتشاف صلاحيات Root على هذا الجهاز، وقد يؤدي ذلك إلى إضعاف الحماية.",
        "هیچ نیشانەیەکی Root نەدۆزرایەوە." to "لم يتم العثور على أي علامة لصلاحيات Root.", "باشە" to "حسناً",
        "مێژووی پاراستن" to "سجل الحماية", "ڕۆژانە" to "يومي", "هەفتانە" to "أسبوعي", "مانگانە" to "شهري",
        "کۆی بلۆککردنەکان" to "إجمالي عمليات الحظر", "دوایین ڕووداوەکان" to "أحدث الأحداث",
        "هێشتا هیچ شتێک بلۆک نەکراوە" to "لم يتم حظر أي شيء بعد", "ڕووداوەکان لێرە دەردەکەون" to "ستظهر الأحداث هنا",
        "Accessibility Service" to "خدمة إمكانية الوصول", "پاراستنی زیادە بۆ براوزەرەکان" to "حماية إضافية للمتصفحات",
        "مۆڵەتی ئەدمین" to "مسؤول الجهاز", "مۆڵەت دراوە - بەڕێوەبردن لە Settings ـی ئەندرۆید" to "ممنوح — الإدارة من إعدادات Android",
        "بەڕێوەبردن لە Settings ـی ئەندرۆید" to "الإدارة من إعدادات Android", "تایبەتمەندی" to "الخصوصية",
        "BlockX LaAbrah تەنها ناونیشانی تۆڕ و دەقی دیاریکراوی براوزەر دەپشکنێت. هیچ داتایەک بۆ سێرڤەری تایبەت نانێردرێت و مێژوو لەسەر ئامێرەکەت دەمێنێتەوە." to "يفحص BlockX LaAbrah عناوين الاتصال ونصوص المتصفح المحددة فقط. لا تُرسل أي بيانات إلى خادم خاص، ويبقى السجل على جهازك.",
        "BlockX LaAbrah · وەشانی 1.0" to "BlockX LaAbrah · الإصدار 1.0",
        "Item deleted" to "تم حذف العنصر", "%d items deleted" to "تم حذف %d عناصر", "Undo" to "تراجع", "%d selected" to "تم تحديد %d",
        "Clear selection" to "مسح التحديد", "Delete selected" to "حذف المحدد", "AI classification settings" to "إعدادات التصنيف الذكي",
        "Add sites" to "إضافة مواقع", "Search blocklist" to "البحث في قائمة الحظر", "Search whitelist" to "البحث في القائمة البيضاء", "Clear search" to "مسح البحث", "Sort" to "ترتيب",
        "Add items to your blocklist." to "أضف مواقع أو تطبيقات أو كلمات إلى قائمة الحظر.", "Add items to your whitelist." to "أضف مواقع أو تطبيقات أو كلمات إلى القائمة البيضاء.",
        "Try another search or filter." to "جرّب بحثاً أو مرشحاً آخر.", "Delete" to "حذف", "Selected" to "محدد", "Options" to "خيارات", "Website" to "موقع",
        "Add to Blocklist" to "إضافة إلى قائمة الحظر", "Add to Whitelist" to "إضافة إلى القائمة البيضاء", "Sites" to "مواقع", "Words" to "كلمات",
        "Enter one or more domains" to "أدخل نطاقاً واحداً أو أكثر", "Separate domains with a new line, comma, or space." to "افصل النطاقات بسطر جديد أو فاصلة أو مسافة.",
        "Add keywords" to "إضافة كلمات", "Separate multiple keywords with a new line or comma." to "افصل الكلمات بسطر جديد أو فاصلة.",
        "Enter keywords" to "أدخل الكلمات", "Enter at least one domain" to "أدخل نطاقاً واحداً على الأقل", "Invalid domain: %s" to "نطاق غير صالح: %s",
        "Enter at least one keyword" to "أدخل كلمة واحدة على الأقل", "Add %d apps" to "إضافة %d تطبيقات", "Add Apps" to "إضافة تطبيقات", "Add Keywords" to "إضافة كلمات",
        "Smart classification" to "التصنيف الذكي", "Block at %d%% confidence" to "الحظر عند ثقة %d%%", "Done" to "تم",
        "Adult content" to "محتوى للبالغين", "Gambling" to "القمار", "Drugs" to "المخدرات", "Violence" to "العنف", "Hate" to "الكراهية",
        "Scam" to "الاحتيال", "Phishing" to "التصيد", "Malware" to "البرمجيات الضارة", "Extremism" to "التطرف",
        "Blocked keyword" to "كلمة محظورة", "Website rule" to "قاعدة موقع", "Blocked domain" to "نطاق محظور", "Circumvention blocked" to "تم حظر التجاوز",
        // ---- home dashboard ----
        "سڵاو" to "مرحباً",
        "دۆخی پاراستن" to "حالة الحماية",
        "پاراستن چالاکە" to "الحماية مفعّلة",
        "پاراستن لەکارخراوە" to "الحماية متوقفة مؤقتاً",
        "هەموو قەپاغەکان بە باشی کاردەکەن" to "جميع وسائل الحماية تعمل بسلاسة",
        "پاراستن ناچالاکە، پاراستن چالاک بکە" to "الحماية متوقفة، فعّلها للبقاء آمناً",
        "دۆخی پاراستنی ئامێرەکەت لێرەیە" to "حالة حماية جهازك في لمحة",
        "ئاگاداریی ئاسایش" to "تحذير أمني",
        "ئامێرەکە پارێزراوە" to "الجهاز آمن",
        "نیشانەی Root لەم ئامێرە دۆزرایەوە. ئەمە دەتوانێت پاراستن لاواز بکات." to "تم اكتشاف صلاحيات Root على هذا الجهاز، وقد يؤدي ذلك إلى إضعاف الحماية.",
        "هیچ نیشانەیەکی Root نەدۆزرایەوە." to "لم يتم العثور على أي علامة لصلاحيات Root.",
        "باشە" to "حسناً",
        "پاراستنی براوزەر" to "حماية المتصفح",
        "مۆڵەت دراوە" to "تم منح الإذن",
        "پێویستی بە مۆڵەتە" to "الإذن مطلوب",
        "داواکاری پشکنراو" to "طلبات مفحوصة",
        "بلۆککراو" to "محظور",
        // ---- history ----
        "مێژووی پاراستن" to "سجل الحماية",
        "ڕۆژانە" to "يومي", "هەفتانە" to "أسبوعي", "مانگانە" to "شهري",
        "کۆی بلۆککردنەکان" to "إجمالي عمليات الحظر",
        "دوایین ڕووداوەکان" to "أحدث الأحداث",
        "هێشتا هیچ شتێک بلۆک نەکراوە" to "لم يتم حظر أي شيء بعد",
        "ڕووداوەکان لێرە دەردەکەون" to "ستظهر الأحداث هنا",
        // ---- settings ----
        "ڕێکخستن" to "الإعدادات",
        "هەموو قەپاغەکانی پاراستن لێرەیە" to "جميع وسائل الحماية هنا",
        "ڕووکار، زمان و تێبینیەکان" to "المظهر واللغة والتفضيلات",
        "دۆخی ڕووکار" to "المظهر",
        "سیستەم" to "النظام", "ڕووناک" to "فاتح", "تاریک" to "داكن",
        "زمان" to "اللغة",
        "تایبەتمەندی" to "الخصوصية",
        "BlockX LaAbrah تەنها ناونیشانی تۆڕ و دەقی دیاریکراوی براوزەر دەپشکنێت. هیچ داتایەک بۆ سێرڤەری تایبەت نانێردرێت و مێژوو لەسەر ئامێرەکەت دەمێنێتەوە." to "يفحص BlockX LaAbrah عناوين الاتصال ونصوص المتصفح المحددة فقط. لا تُرسل أي بيانات إلى خادم خاص، ويبقى السجل على جهازك.",
        "BlockX LaAbrah · وەشانی 2.1.11" to "BlockX LaAbrah · الإصدار 2.1.11",
        "مۆڵەتی ئەدمین" to "مسؤول الجهاز",
        "مۆڵەت دراوە - بەڕێوەبردن لە Settings ـی ئەندرۆید" to "ممنوح — الإدارة من إعدادات Android",
        "بەڕێوەبردن لە Settings ـی ئەندرۆید" to "الإدارة من إعدادات Android",
        "Accessibility Service" to "خدمة إمكانية الوصول",
        "پاراستنی زیادە بۆ براوزەرەکان" to "حماية إضافية للمتصفحات",
        "فێرکاری مۆڵەتەکان" to "دليل الأذونات",
        "هەنگاوەکانی Accessibility و Device Admin و باتری ببینەوە." to "راجع خطوات إمكانية الوصول ومسؤول الجهاز والبطارية.",
        "وەستاندنی پاراستن (٣ خولەک)" to "إيقاف الحماية (٣ دقائق)",
        "دوای %d خولەک دەگەڕێتەوە - بۆ گەڕانەوە دەستبکە" to "تعود خلال %d دقيقة — اضغط للاستئناف الآن",
        "کاتی دەیکوژێنێتەوە، خۆکارانە دەگەڕێتەوە" to "إيقاف مؤقت، تعود تلقائياً",
        "هیچ داتایەک بۆ سێرڤەر نانێردرێت؛ هەموو شتێک لەسەر ئامێرەکەت دەمێنێتەوە." to "لا تُرسل أي بيانات إلى خادم؛ كل شيء يبقى على جهازك.",
    )
    val resolver: (String, String) -> String = { key, language ->
        when (language) {
            "en" -> en[key] ?: key
            "ar" -> ar[key] ?: key
            else -> ku[key] ?: key
        }
    }
    resolver
}

fun appText(key: String, language: String): String = textResolver(key, language)
